#!/usr/bin/python3
def raise_exception():
    return 'a' + 1
